services:
  rvc:
    image: rvc-webui:latest
    container_name: rvc-webui
    build: .s
    working_dir: /app
    volumes:
      - .:/app
      - ${HF_HOME}:/root/.cache/huggingface
      - ${TORCH_HOME}:/root/.cache/torch

    ports:
      - ${RVC_WEBUI_PORT}:7865
    command: [ "python", "infer-web.py" ]
    shm_size: "2g"
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
