services:
  rvc:
    image: rvc-webui:latest
    container_name: rvc-webui
    build: .s
    working_dir: /app
    volumes:
      - .:/app
      - ${HOME}/.cache:/root/.cache
    ports:
      - 8202:7865
    command: [ "python", "infer-web.py" ]
    shm_size: "2g"
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
